// REGISTER
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
// LOADER
export const SET_INITAL_LOADING = "SET_INITAL_LOADING";
export const SET_INIT_STATE = "SET_INIT_STATE";

// COMPANY (Umesto Receive da ide RESPONSE)
export const REQUEST_ALL_COMPANY = "REQUEST_ALL_COMPANY";
export const RECEIVE_ALL_COMPANY = "RECEIVE_ALL_COMPANY";
export const CREATE_NEW_COMPANY = "CREATE_NEW_COMPANY";
// LOGIN
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const SET_LOGIN_USER = "SET_LOGIN_USER";
// LOGOUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// PROFILE
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_RECEIVE = "FETCH_PROFILE_RECEIVE";
export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_RESPONSE = "EDIT_USER_RESPONSE";
