export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const SET_INITAL_LOADING = "SET_INITAL_LOADING";
export const REQUEST_ALL_COMPANY = "REQUEST_ALL_COMPANY";
export const RECEIVE_ALL_COMPANY = "RECEIVE_ALL_COMPANY";
